// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TradeCore.Console.Data;

#nullable disable

namespace TradeCore.Api.Migrations;

[DbContext(typeof(TradeCoreDbContext))]
[Migration("20260818000000_AddPortfolioTransfers")]
partial class AddPortfolioTransfers
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "10.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);
        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("TradeCore.Console.Models.PortfolioTransfer", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<Guid>("AccountId").HasColumnType("uuid");
            b.Property<decimal>("AveragePrice").HasPrecision(18, 4).HasColumnType("numeric(18,4)");
            b.Property<DateTime?>("CompletedAt").HasColumnType("timestamp with time zone");
            b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<int>("Quantity").HasColumnType("integer");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
            b.Property<Guid>("StockId").HasColumnType("uuid");
            b.HasKey("Id");
            b.HasIndex("AccountId");
            b.HasIndex("StockId");
            b.ToTable("PortfolioTransfers", (string)null);
        });
#pragma warning restore 612, 618
    }
}
