apiVersion: v1
kind: Service
metadata:
  name: tradecore-api
  labels:
    app.kubernetes.io/name: tradecore-api
    app.kubernetes.io/part-of: tradecore
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tradecore-api
    app.kubernetes.io/part-of: tradecore
  ports:
    - name: http
      port: 8080
      targetPort: http
